blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/dgrauet/smeltr/discussions
    about: For open-ended questions and discussion, please use Discussions instead of Issues.
